const UPDATE_TOKEN = "UPDATE_TOKEN";
const TOKEN_SENT = "TOKEN_SENT";
const UPDATE_COUNT = "UPDATE_COUNT";

const ADD_RESOURCE = "ADD_RESOURCE";
const UPDATE_RESOURCE = "UPDATE_RESOURCE";
const DELETE_RESOURCE = "REMOVE_RESOURCE";
const PURGE = "PURGE";

export { TOKEN_SENT, UPDATE_COUNT, UPDATE_TOKEN, ADD_RESOURCE, UPDATE_RESOURCE, DELETE_RESOURCE, PURGE };
